### ISSUE TITLE
I am Getting This Error Running on(Win7 64Bit)(node-8.12.0,npm-6.4.1).Help Me To Resolve This Issue.

### ISSUE THREAD

**Issue by maniv95** [OriginProtocol/origin-playground#18]
F:\Solidity\origin-playground>npm start
> identity-playground@0.1.0 start F:\Solidity\origin-playground
> node -r @babel/register index
Ganache listening. Starting webpack...
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: spawn ./node_modules/.bin/webpack-dev-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! identity-playground@0.1.0 start: `node -r @babel/register index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the identity-playground@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by melvinhicks** [comment]
Also receiving this error. Windows 10, Node 10.10.0

**Comment by solinter** [comment]
Receive this error on Windows 10, but for me works on Ubuntu 16 Node 10 (from virtual machine).

Is an issue for Windows.
